/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Universidad.Vistas;

import Universidad.Modelo.Conexion;
import Universidad.Modelo.Usuario;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author EL MEGAS
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private static Usuario user;
    private Conexion conexion;

    /**
     * Creates new form MenuPrincipal
     */
    
    /* Inicié una vista de inicio en el constructor, ESTA A PRUEBA POR FUNCIONALIDAD.... FUNCIONAAAAAAAAAAAAAAA */
    public MenuPrincipal() {
        initComponents();
        
        try {
            conexion = new Conexion();
        } catch (ClassNotFoundException ex) {
            System.out.println("No se pudo crear conexion");
        }
        
        if (user == null){
            VistaInicio vistaInit = new VistaInicio(conexion);
            jDesktopPane.removeAll();
            jDesktopPane.moveToFront(vistaInit);
            jDesktopPane.repaint();
            jDesktopPane.add(vistaInit);

            vistaInit.setVisible(true);
        } else {
            VistaMenuAlumno vistaMenuAlumno = new VistaMenuAlumno(user);
            
            jDesktopPane.removeAll();
            jDesktopPane.moveToFront(vistaMenuAlumno);
            jDesktopPane.repaint();
            jDesktopPane.add(vistaMenuAlumno);

            vistaMenuAlumno.setVisible(true);
        }
    }
    
    public MenuPrincipal(Usuario user) {
        initComponents();
        
        try {
            conexion = new Conexion();
        } catch (ClassNotFoundException ex) {
            System.out.println("No se pudo crear conexion");
        }
        
        VistaMenuAlumno vistaMenuAlumno = new VistaMenuAlumno(user);
            
        jDesktopPane.removeAll();
        jDesktopPane.moveToFront(vistaMenuAlumno);
        jDesktopPane.repaint();
        jDesktopPane.add(vistaMenuAlumno);
        vistaMenuAlumno.setVisible(true);
    }
    
    public void agregarVentana(JInternalFrame subVentana) {
       
       this.jDesktopPane1.add(subVentana);
       
        subVentana.toFront();
        subVentana.setVisible(true);
    }
    
    public static void setIngreso(Usuario user){
        MenuPrincipal.user = user;
    }
    
    public Usuario getUser(){
        return MenuPrincipal.user;
    }
    
    public void sesionAlumno(Usuario usuario){
        VistaMenuAlumno vistaMenuAlumno = new VistaMenuAlumno(usuario);
        jDesktopPane.removeAll();
        jDesktopPane.moveToFront(vistaMenuAlumno);
        jDesktopPane.repaint();
        jDesktopPane.add(vistaMenuAlumno);

        vistaMenuAlumno.setVisible(true);
    }
    
    public void sesionDocente(Usuario usuario){
        VistaMenuDocente vistaMenuDocente = new VistaMenuDocente(usuario);
        jDesktopPane.removeAll();
        jDesktopPane.moveToFront(vistaMenuDocente);
        jDesktopPane.repaint();
        jDesktopPane.add(vistaMenuDocente);

        vistaMenuDocente.setVisible(true);
    }
    
    public void iniciarSesion(Usuario user){
        if ("Alumno".equals(user.getRolUsuario())){
            this.sesionAlumno(user);
        } else if ("Docente".equals(user.getRolUsuario())){
            this.sesionDocente(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
