/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Universidad.Vistas;

import Universidad.Control.*;
import Universidad.Modelo.Usuario;

/**
 *
 * @author Agostina
 */
public class VistaMenuDocente extends javax.swing.JInternalFrame {
    private Usuario user;
    private AlumnoData alumnoData;
    private MateriaData materiaData;
    private InscripcionData inscripcionData;
    private UsuarioData usuarioData;
    private MenuPrincipal menu;

    /**
     * Creates new form VistaMenuDocente
     */
    public VistaMenuDocente(MenuPrincipal menu, Usuario user, AlumnoData alumnoData, MateriaData materiaData, InscripcionData inscripcionData, UsuarioData usuarioData) {
        initComponents();
        
        this.user = user;
        this.alumnoData = alumnoData;
        this.materiaData = materiaData;
        this.inscripcionData = inscripcionData;
        this.usuarioData = usuarioData;
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonListarMaterias = new javax.swing.JButton();
        jButtonListarAlumnos = new javax.swing.JButton();
        jButtonRegCalificacion = new javax.swing.JButton();
        jButtonNuevoAlumno = new javax.swing.JButton();
        jButtonBajaAlumno = new javax.swing.JButton();
        jButtonVerModMateria = new javax.swing.JButton();
        jButtonBajaMateria = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonVerAlumnos = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bienvenido Docente");

        jButtonListarMaterias.setBackground(new java.awt.Color(153, 153, 153));
        jButtonListarMaterias.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonListarMaterias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarMaterias.setText("Listar Materias por Alumno");
        jButtonListarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarMateriasActionPerformed(evt);
            }
        });

        jButtonListarAlumnos.setBackground(new java.awt.Color(153, 153, 153));
        jButtonListarAlumnos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonListarAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarAlumnos.setText("Listar Alumnos por Materia");
        jButtonListarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarAlumnosActionPerformed(evt);
            }
        });

        jButtonRegCalificacion.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRegCalificacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonRegCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegCalificacion.setText("Registrar calificacion final");
        jButtonRegCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegCalificacionActionPerformed(evt);
            }
        });

        jButtonNuevoAlumno.setBackground(new java.awt.Color(153, 153, 153));
        jButtonNuevoAlumno.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonNuevoAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevoAlumno.setText("Agregar o Modifcar Alumno");
        jButtonNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoAlumnoActionPerformed(evt);
            }
        });

        jButtonBajaAlumno.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBajaAlumno.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonBajaAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBajaAlumno.setText("Dar de Baja Alumno");

        jButtonVerModMateria.setBackground(new java.awt.Color(153, 153, 153));
        jButtonVerModMateria.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonVerModMateria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerModMateria.setText("Agregar o Modificar Materia");
        jButtonVerModMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerModMateriaActionPerformed(evt);
            }
        });

        jButtonBajaMateria.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBajaMateria.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonBajaMateria.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBajaMateria.setText("Dar de Baja Materia");

        jButtonSalir.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSalir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonVerAlumnos.setBackground(new java.awt.Color(153, 153, 153));
        jButtonVerAlumnos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonVerAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerAlumnos.setText("Ver alumnos");
        jButtonVerAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jButtonListarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRegCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBajaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVerAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBajaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerModMateria))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonListarMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegCalificacion)
                .addGap(18, 18, 18)
                .addComponent(jButtonNuevoAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBajaAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerModMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBajaMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        menu.iniciarSesion(user);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonListarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarMateriasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonListarMateriasActionPerformed

    private void jButtonListarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarAlumnosActionPerformed
        // TODO add your handling code here:
        menu.verInscriptosPorMateria();
    }//GEN-LAST:event_jButtonListarAlumnosActionPerformed

    private void jButtonRegCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegCalificacionActionPerformed
        // TODO add your handling code here:
        menu.verVerModNotas();
    }//GEN-LAST:event_jButtonRegCalificacionActionPerformed

    private void jButtonNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        menu.verVerModAlumno();
    }//GEN-LAST:event_jButtonNuevoAlumnoActionPerformed

    private void jButtonVerModMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerModMateriaActionPerformed
        // TODO add your handling code here:
        menu.verVerModMateria();
    }//GEN-LAST:event_jButtonVerModMateriaActionPerformed

    private void jButtonVerAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerAlumnosActionPerformed
        // TODO add your handling code here:
        menu.verVistaVerAlumnos();
    }//GEN-LAST:event_jButtonVerAlumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBajaAlumno;
    private javax.swing.JButton jButtonBajaMateria;
    private javax.swing.JButton jButtonListarAlumnos;
    private javax.swing.JButton jButtonListarMaterias;
    private javax.swing.JButton jButtonNuevoAlumno;
    private javax.swing.JButton jButtonRegCalificacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerAlumnos;
    private javax.swing.JButton jButtonVerModMateria;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
